language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

install:
  - composer self-update
  - composer --version
  - php -v
  - composer install --prefer-dist

script:
  - composer run analyze
  - composer run test

after_success:
  - |
    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
    php php-coveralls.phar --verbose;